<?php
// helpers.php - shared formatting helpers
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['currency_select'])) {
    $selectedCurrency = strtoupper(trim($_POST['currency_select']));
    if (in_array($selectedCurrency, ['BDT', 'CNY', 'USD'], true)) {
        $_SESSION['currency'] = $selectedCurrency;
    }
}

function zicture_currency(): string {
    return $_SESSION['currency'] ?? 'BDT';
}

function zicture_money(float $amountBdt): string {
    $currency = zicture_currency();
    $rates = [
        'BDT' => ['symbol' => 'Tk', 'rate' => 1, 'decimals' => 0],
        'CNY' => ['symbol' => '¥', 'rate' => 0.061, 'decimals' => 2],
        'USD' => ['symbol' => '$', 'rate' => 0.0085, 'decimals' => 2],
    ];
    $meta = $rates[$currency] ?? $rates['BDT'];
    return $meta['symbol'] . ' ' . number_format($amountBdt * $meta['rate'], $meta['decimals']);
}

function zicture_plain_money(float $amountBdt): string {
    return zicture_money($amountBdt) . ' (' . zicture_currency() . ')';
}

function zicture_categories(): array {
    return [
        'all' => ['label' => 'All Products', 'icon' => 'th', 'color' => 'text-primary'],
        'food' => ['label' => 'Food', 'icon' => 'utensils', 'color' => 'text-danger'],
        'games' => ['label' => 'Games', 'icon' => 'gamepad', 'color' => 'text-primary'],
        'clothes' => ['label' => 'Clothes', 'icon' => 'shirt', 'color' => 'text-info'],
        'medicine' => ['label' => 'Medicine', 'icon' => 'pills', 'color' => 'text-success'],
        'software' => ['label' => 'Software', 'icon' => 'code', 'color' => 'text-secondary'],
        'kids' => ['label' => 'Kids', 'icon' => 'child-reaching', 'color' => 'text-warning'],
        'machineries' => ['label' => 'Machineries', 'icon' => 'screwdriver-wrench', 'color' => 'text-dark'],
        'electronics' => ['label' => 'Electronics', 'icon' => 'laptop', 'color' => 'text-primary'],
        'books' => ['label' => 'Books', 'icon' => 'book-open', 'color' => 'text-success'],
        'beauty' => ['label' => 'Beauty', 'icon' => 'spa', 'color' => 'text-danger'],
        'home' => ['label' => 'Home & Living', 'icon' => 'house', 'color' => 'text-success'],
        'sports' => ['label' => 'Sports', 'icon' => 'dumbbell', 'color' => 'text-primary'],
        'automotive' => ['label' => 'Automotive', 'icon' => 'car', 'color' => 'text-secondary'],
        'stationery' => ['label' => 'Stationery', 'icon' => 'pen-nib', 'color' => 'text-info'],
    ];
}

function zicture_category_label(string $category): string {
    $categories = zicture_categories();
    return $categories[$category]['label'] ?? ucwords(str_replace(['-', '_'], ' ', $category));
}

function zicture_customer_initials(): string {
    $name = trim($_SESSION['customer_name'] ?? 'Guest Shopper');
    $parts = preg_split('/\s+/', $name);
    $initials = '';
    foreach ($parts as $part) {
        if ($part !== '') {
            $initials .= strtoupper(substr($part, 0, 1));
        }
        if (strlen($initials) >= 2) {
            break;
        }
    }
    return $initials ?: 'ZS';
}

function zicture_customer_avatar(): string {
    return $_SESSION['customer_avatar'] ?? '';
}

function zicture_pdf_escape(string $text): string {
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
}

function zicture_send_text_pdf(array $lines, string $filename, string $heading = 'Zicture'): void {
    $pageWidth = 612;
    $pageHeight = 842;
    $left = 46;
    $top = 760;
    $lineHeight = 15;
    $maxChars = 88;
    $pages = [];
    $content = '';
    $y = $top;

    $startPage = function () use (&$content, &$y, $pageWidth, $pageHeight, $heading, $left, $top) {
        $y = $top;
        $content = "0.96 0.98 1 rg\n0 0 {$pageWidth} {$pageHeight} re f\n";
        $content .= "0.06 0.09 0.16 rg\n0 " . ($pageHeight - 92) . " {$pageWidth} 92 re f\n";
        $content .= "1 0.76 0.03 rg\n46 " . ($pageHeight - 80) . " 70 5 re f\n";
        $content .= "BT\n/F2 22 Tf\n1 1 1 rg\n{$left} " . ($pageHeight - 58) . " Td\n(" . zicture_pdf_escape($heading) . ") Tj\n";
        $content .= "/F1 9 Tf\n0 -18 Td\n(Generated by Zicture - The Online Shopping) Tj\nET\n";
        $content .= "BT\n/F1 10 Tf\n0.1 0.13 0.2 rg\n{$left} {$top} Td\n";
    };

    $finishPage = function () use (&$pages, &$content, $pageWidth) {
        $content .= "ET\n";
        $content .= "BT\n/F1 8 Tf\n0.4 0.45 0.52 rg\n46 26 Td\n(Zicture keeps shopping, billing, and catalog records ready for download.) Tj\n";
        $content .= ($pageWidth - 120) . " 0 Td\n(Page " . (count($pages) + 1) . ") Tj\nET\n";
        $pages[] = $content;
    };

    $writeLine = function (string $line, bool $bold = false) use (&$content, &$y, $lineHeight, $left) {
        $font = $bold ? 'F2' : 'F1';
        $content .= "/{$font} " . ($bold ? '12' : '10') . " Tf\n";
        $content .= '(' . zicture_pdf_escape($line) . ") Tj\n0 -" . ($bold ? 19 : $lineHeight) . " Td\n";
        $y -= $bold ? 19 : $lineHeight;
    };

    $startPage();
    foreach ($lines as $rawLine) {
        $line = trim((string)$rawLine);
        $isHeading = str_starts_with($line, '## ');
        if ($isHeading) {
            $line = substr($line, 3);
        }
        $wrapped = $line === '' ? [''] : explode("\n", wordwrap($line, $maxChars, "\n", true));
        foreach ($wrapped as $index => $wrappedLine) {
            if ($y < 72) {
                $finishPage();
                $startPage();
            }
            $writeLine($wrappedLine, $isHeading && $index === 0);
        }
    }
    $finishPage();

    $objects = [];
    $objects[] = "<< /Type /Catalog /Pages 2 0 R >>";
    $objects[] = "<< /Type /Pages /Kids [] /Count 0 >>";
    $kids = [];
    $fontObjectNumber = 3 + (count($pages) * 2);
    foreach ($pages as $index => $pageContent) {
        $pageObjectNumber = 3 + ($index * 2);
        $contentObjectNumber = $pageObjectNumber + 1;
        $kids[] = $pageObjectNumber . " 0 R";
        $objects[] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {$pageWidth} {$pageHeight}] /Resources << /Font << /F1 {$fontObjectNumber} 0 R /F2 " . ($fontObjectNumber + 1) . " 0 R >> >> /Contents {$contentObjectNumber} 0 R >>";
        $objects[] = "<< /Length " . strlen($pageContent) . " >>\nstream\n" . $pageContent . "\nendstream";
    }
    $objects[1] = "<< /Type /Pages /Kids [" . implode(' ', $kids) . "] /Count " . count($pages) . " >>";
    $objects[] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
    $objects[] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $i => $object) {
        $offsets[] = strlen($pdf);
        $pdf .= ($i + 1) . " 0 obj\n" . $object . "\nendobj\n";
    }
    $xref = strlen($pdf);
    $pdf .= "xref\n0 " . (count($objects) + 1) . "\n0000000000 65535 f \n";
    for ($i = 1; $i <= count($objects); $i++) {
        $pdf .= str_pad((string)$offsets[$i], 10, '0', STR_PAD_LEFT) . " 00000 n \n";
    }
    $pdf .= "trailer\n<< /Size " . (count($objects) + 1) . " /Root 1 0 R >>\nstartxref\n" . $xref . "\n%%EOF";

    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . basename($filename) . '"');
    echo $pdf;
    exit;
}
?>
